micronaut:
  application:
    name: demo
  server:
    port: 9090
  caches:
    cache-1h:
      listen-to-removals: true
      expire-after-access: 60m

netty:
  default:
    allocator:
      max-order: 3
